export const ACTIONS = {
    ROOM_JOIN: "ROOM_JOIN",
    USER_JOINED: "USER_JOINED",
    USER_CALL: "USER_CALL",
    INCOMING_CALL: "INCOMING_CALL",
    CALL_ACCEPTED: "CALL_ACCEPTED",
    PEER_NEGO_NEEDED: "PEER_NEGO_NEEDED",
    PEER_NEGO_DONE: "PEER_NEGO_DONE",
    CODE_CHANGE: "CODE_CHANGE",
};
